apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
- ../base

namespace: ocellus-prod

images:
- name: ocellus-image-name
  newName: registry.deeplerg.dev/ocellus
  newTag: prod-6b8ca399

configMapGenerator:
- behavior: create
  envs:
  - environment-variables.env
  name: environment-variables
- behavior: create
  literals:
  - NAME=ocellus-prod
  name: namespace
- literals:
  - NAME=docker-registry-cred-ocellus-prod
  name: registry-secrets

replacements:
- source:
    fieldPath: data.NAME
    kind: ConfigMap
    name: namespace
  targets:
  - fieldPaths:
    - metadata.name
    select:
      kind: Namespace
- source:
    fieldPath: data.NAME
    kind: ConfigMap
    name: registry-secrets
  targets:
  - fieldPaths:
    - spec.template.spec.imagePullSecrets.0.name
    select:
      kind: Deployment
- source:
    fieldPath: data.GATEWAY_NAME
    kind: ConfigMap
    name: environment-variables
  targets:
  - fieldPaths:
    - spec.parentRefs.0.name
    select:
      kind: HTTPRoute
- source:
    fieldPath: data.GATEWAY_NAMESPACE
    kind: ConfigMap
    name: environment-variables
  targets:
  - fieldPaths:
    - spec.parentRefs.0.namespace
    select:
      kind: HTTPRoute
- source:
    fieldPath: data.GATEWAY_HOST
    kind: ConfigMap
    name: environment-variables
  targets:
  - fieldPaths:
    - spec.hostnames.0
    select:
      kind: HTTPRoute
